import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HomeView from '@/components/Home/Home';
const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Challenge Esto es</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <HomeView/>
            </main>
        </div>
    );
};

export default Home;
