import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HomeView from '@/components/Home/HomeView';
const Home: NextPage = () => {
    return (
        <div className="flex flex-row justify-center xl:items-center items-start  container mx-auto min-h-screen h-full w-full">
            <Head>
                <title>Challenge Esto Es</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeView />
        </div>
    );
};

export default Home;
